from datetime import datetime
from pathlib import Path

from .config import get_config


FALLBACK_DIR_NAME = ".agent-memory"
FALLBACK_FILE_NAME = "memory.md"


def is_obsidian_enabled() -> bool:
    config = get_config()
    return bool(config.get("use_obsidian") and config.get("obsidian_vault"))


def get_memory_dir(project_root: Path | None = None) -> Path:
    resolved_project_root = (project_root or Path.cwd()).resolve()
    if is_obsidian_enabled():
        vault = Path(get_config()["obsidian_vault"])
        memory_dir = vault / "Memory" / "Agent-Mem"
    else:
        memory_dir = resolved_project_root / FALLBACK_DIR_NAME

    memory_dir.mkdir(parents=True, exist_ok=True)
    return memory_dir


def get_fallback_memory_file(project_root: Path | None = None) -> Path:
    return get_memory_dir(project_root) / FALLBACK_FILE_NAME


def _session_block(project_name: str, summary: str) -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f"""## Session Summary - {timestamp}

Project: {project_name}

{summary}

---
**Auto-generated by agent-mem**
"""


def write_session_summary(project_name: str, summary: str, project_root: Path | None = None) -> str:
    resolved_project_root = (project_root or Path.cwd()).resolve()
    memory_dir = get_memory_dir(resolved_project_root)
    date_str = datetime.now().strftime("%Y-%m-%d_%H-%M")

    if is_obsidian_enabled():
        filepath = memory_dir / f"{project_name}-{date_str}-session.md"
        content = f"""# Session Summary - {datetime.now().strftime("%Y-%m-%d %H:%M")}

{summary}

---
**Auto-generated by agent-mem • Obsidian mode**
"""
        filepath.write_text(content, encoding="utf-8")
        vault = Path(get_config()["obsidian_vault"])
        return str(filepath.relative_to(vault))

    filepath = get_fallback_memory_file(resolved_project_root)
    entry = _session_block(project_name, summary).strip() + "\n"
    if filepath.exists():
        filepath.write_text(filepath.read_text(encoding="utf-8") + "\n" + entry, encoding="utf-8")
    else:
        filepath.write_text("# Agent Memory\n\n" + entry, encoding="utf-8")
    return str(filepath.relative_to(resolved_project_root))


def list_recent_session_files(
    project_name: str,
    count: int = 3,
    project_root: Path | None = None,
) -> list[Path]:
    resolved_project_root = (project_root or Path.cwd()).resolve()
    if is_obsidian_enabled():
        memory_dir = get_memory_dir(resolved_project_root)
        files = sorted(
            memory_dir.glob(f"{project_name}*.md"),
            key=lambda path: path.stat().st_mtime,
            reverse=True,
        )
        return files[:count]

    fallback_file = get_fallback_memory_file(resolved_project_root)
    return [fallback_file] if fallback_file.exists() else []